// AUTO-GENERATED by backend/scripts/generate_streaming_types.py. DO NOT EDIT.

export type StreamEventType = "user_message" | "assistant_delta" | "assistant_message" | "assistant_final" | "message_start" | "message_delta" | "message_section_end" | "section_end" | "reasoning_start" | "reasoning_delta" | "reasoning_section_end" | "tool_start" | "tool_delta" | "tool_end" | "tool_batch_start" | "tool_batch_end" | "observation_start" | "observation_delta" | "observation_section_end" | "retry_start" | "retry_attempt" | "graph_interrupt" | "plan_created" | "todo_progress" | "stream_error" | "status" | "agent_pause_request" | "intent_summary";

export interface StreamEventMetadata {
  conversation_id?: string | null;
  conversationId?: string | null;
  id?: string | null;
  step_type?: string | null;
  ind?: number | null;
  sequence?: number | null;
  turn_sequence?: number | null;
  phase_sequence?: number | null;
  reasoning_section_id?: string | null;
  streaming?: boolean | null;
  section_name?: string | null;
  tool?: string | null;
  tool_name?: string | null;
  tool_call_id?: string | null;
  tool_batch_id?: string | null;
  parameters?: Record<string, unknown> | null;
  status?: string | null;
  command?: string | null;
  retry_attempt?: number | null;
  retry_max_attempts?: number | null;
  failure_category?: string | null;
  error?: string | null;
  subtype?: string | null;
  internal_only?: boolean | null;
  requires_user_action?: boolean | null;
  role?: string | null;
  message_type?: string | null;
  timestamp?: number | string | null;
  [key: string]: unknown;
}

export interface StreamEvent {
  type: StreamEventType;
  content: string;
  metadata?: StreamEventMetadata;
  sequence?: number;
  task_id?: number;
  timestamp?: string;
  [key: string]: unknown;
}

export type UserMessageEvent = StreamEvent & { type: "user_message" };
export type AssistantDeltaEvent = StreamEvent & { type: "assistant_delta" };
export type AssistantMessageEvent = StreamEvent & { type: "assistant_message" };
export type AssistantFinalEvent = StreamEvent & { type: "assistant_final" };
export type MessageStartEvent = StreamEvent & { type: "message_start" };
export type MessageDeltaEvent = StreamEvent & { type: "message_delta" };
export type MessageSectionEndEvent = StreamEvent & { type: "message_section_end" };
export type SectionEndEvent = StreamEvent & { type: "section_end" };
export type ReasoningStartEvent = StreamEvent & { type: "reasoning_start" };
export type ReasoningDeltaEvent = StreamEvent & { type: "reasoning_delta" };
export type ReasoningSectionEndEvent = StreamEvent & { type: "reasoning_section_end" };
export type ToolStartEvent = StreamEvent & { type: "tool_start" };
export type ToolDeltaEvent = StreamEvent & { type: "tool_delta" };
export type ToolEndEvent = StreamEvent & { type: "tool_end" };
export type ToolBatchStartEvent = StreamEvent & { type: "tool_batch_start" };
export type ToolBatchEndEvent = StreamEvent & { type: "tool_batch_end" };
export type ObservationStartEvent = StreamEvent & { type: "observation_start" };
export type ObservationDeltaEvent = StreamEvent & { type: "observation_delta" };
export type ObservationSectionEndEvent = StreamEvent & { type: "observation_section_end" };
export type RetryStartEvent = StreamEvent & { type: "retry_start" };
export type RetryAttemptEvent = StreamEvent & { type: "retry_attempt" };
export interface GraphInterruptEvent extends StreamEvent {
  type: "graph_interrupt";
  thread_id?: string;
  interrupt_id?: string;
  checkpoint_id?: string;
  interrupt_type?: "tool_approval" | "plan_review" | "clarify_request";
  payload?: Record<string, unknown>;
  graph_name?: string;
}
export type PlanCreatedEvent = StreamEvent & { type: "plan_created" };
export type TodoProgressEvent = StreamEvent & { type: "todo_progress" };
export type StreamErrorEvent = StreamEvent & { type: "stream_error" };
export type StatusEvent = StreamEvent & { type: "status" };
export type AgentPauseRequestEvent = StreamEvent & { type: "agent_pause_request" };
export type IntentSummaryEvent = StreamEvent & { type: "intent_summary" };

export type PacketObj = UserMessageEvent | AssistantDeltaEvent | AssistantMessageEvent | AssistantFinalEvent | MessageStartEvent | MessageDeltaEvent | MessageSectionEndEvent | SectionEndEvent | ReasoningStartEvent | ReasoningDeltaEvent | ReasoningSectionEndEvent | ToolStartEvent | ToolDeltaEvent | ToolEndEvent | ToolBatchStartEvent | ToolBatchEndEvent | ObservationStartEvent | ObservationDeltaEvent | ObservationSectionEndEvent | RetryStartEvent | RetryAttemptEvent | GraphInterruptEvent | PlanCreatedEvent | TodoProgressEvent | StreamErrorEvent | StatusEvent | AgentPauseRequestEvent | IntentSummaryEvent;

export interface Placement {
  turn_index: number;
  tab_index?: number;
  sub_turn_index?: number | null;
  [key: string]: unknown;
}

export interface Packet {
  placement: Placement;
  obj: PacketObj;
  sequence?: number;
  task_id?: number;
  conversation_id?: string;
  turn_id?: string;
  [key: string]: unknown;
}

export type StreamPacket = Packet;

export function isStreamPacket(value: unknown): value is StreamPacket {
  if (!value || typeof value !== "object") {
    return false;
  }
  const candidate = value as StreamPacket;
  return Boolean(candidate.placement && candidate.obj);
}
