"""
Shared LLM policy contracts and resolvers.

This package hosts canonical cross-runtime LLM role policy definitions to keep
backend and agent behavior aligned under a single authority.
"""

from .role_policy import (
    CANONICAL_REASONING_EFFORT_VALUES,
    DEFAULT_CONVERSATION_MAIN_MODEL,
    DEFAULT_INTERNAL_REASONING_EFFORT,
    DEFAULT_USER_SELECTED_REASONING_EFFORT,
    ModelRoleRegistry,
    ProviderModelBinding,
    ROLE_CONVERSATION_MAIN,
    ROLE_INTENT_CLASSIFIER,
    ROLE_POST_TOOL_ARTICULATOR,
    ROLE_POST_TOOL_OBSERVATION,
    ROLE_REASONING_MAIN,
    ROLE_TOOL_CATEGORY_SELECTOR,
    ROLE_TOOL_OUTPUT_COMPRESSOR,
    RoleCallSettings,
    RoleKey,
    ReasoningEffort,
    validate_reasoning_effort_for_model,
)
from .runtime_selection import (
    DeploymentRef,
    LLMRuntimeSelectionV2,
    deployment_runtime_selection_identity,
    has_versioned_runtime_selection_marker,
    project_checkpoint_runtime_selection,
)
from .timeout_runtime import (
    LLMTimeoutError,
    format_timeout_log_message,
    iter_with_idle_timeout,
    log_timeout_event,
    wait_for_with_timeout,
)
from .timeouts import (
    DEFAULT_LLM_TIMEOUT_SEC,
    LLM_STREAM_IDLE_TIMEOUT_CONVERSATION_MAIN_SEC,
    LLM_STREAM_IDLE_TIMEOUT_POST_TOOL_ARTICULATOR_SEC,
    LLM_STREAM_IDLE_TIMEOUT_POST_TOOL_OBSERVATION_SEC,
    LLM_TIMEOUT_CONTEXT_COMPRESSOR_SEC,
    LLM_TIMEOUT_CONVERSATION_MAIN_SEC,
    LLM_TIMEOUT_INTENT_CLASSIFIER_SEC,
    LLM_TIMEOUT_KNOWLEDGE_CANDIDATE_EXTRACTION_SEC,
    LLM_TIMEOUT_MEMORY_EXTRACTION_SEC,
    LLM_TIMEOUT_MEMORY_GATE_SEC,
    LLM_TIMEOUT_PLANNER_PARAMETER_RESOLUTION_SEC,
    LLM_TIMEOUT_PLANNER_TOOL_SELECTION_SEC,
    LLM_TIMEOUT_POST_TOOL_ARTICULATOR_SEC,
    LLM_TIMEOUT_POST_TOOL_OBSERVATION_SEC,
    LLM_TIMEOUT_REFLECT_SEC,
    LLM_TIMEOUT_REASONING_MAIN_SEC,
    LLM_TIMEOUT_TOOL_CATEGORY_SELECTOR_SEC,
    LLM_TIMEOUT_TOOL_OUTPUT_COMPRESSOR_SEC,
    read_llm_timeout_planner_parameter_resolution_sec,
    read_llm_timeout_planner_tool_selection_sec,
)

__all__ = [
    "CANONICAL_REASONING_EFFORT_VALUES",
    "DEFAULT_CONVERSATION_MAIN_MODEL",
    "DEFAULT_INTERNAL_REASONING_EFFORT",
    "DEFAULT_LLM_TIMEOUT_SEC",
    "DEFAULT_USER_SELECTED_REASONING_EFFORT",
    "DeploymentRef",
    "ModelRoleRegistry",
    "ProviderModelBinding",
    "ROLE_CONVERSATION_MAIN",
    "ROLE_INTENT_CLASSIFIER",
    "ROLE_POST_TOOL_ARTICULATOR",
    "ROLE_POST_TOOL_OBSERVATION",
    "ROLE_REASONING_MAIN",
    "ROLE_TOOL_CATEGORY_SELECTOR",
    "ROLE_TOOL_OUTPUT_COMPRESSOR",
    "RoleCallSettings",
    "RoleKey",
    "ReasoningEffort",
    "format_timeout_log_message",
    "iter_with_idle_timeout",
    "log_timeout_event",
    "LLM_STREAM_IDLE_TIMEOUT_CONVERSATION_MAIN_SEC",
    "LLM_STREAM_IDLE_TIMEOUT_POST_TOOL_ARTICULATOR_SEC",
    "LLM_STREAM_IDLE_TIMEOUT_POST_TOOL_OBSERVATION_SEC",
    "LLMRuntimeSelectionV2",
    "LLMTimeoutError",
    "LLM_TIMEOUT_CONTEXT_COMPRESSOR_SEC",
    "LLM_TIMEOUT_CONVERSATION_MAIN_SEC",
    "LLM_TIMEOUT_INTENT_CLASSIFIER_SEC",
    "LLM_TIMEOUT_KNOWLEDGE_CANDIDATE_EXTRACTION_SEC",
    "LLM_TIMEOUT_MEMORY_EXTRACTION_SEC",
    "LLM_TIMEOUT_MEMORY_GATE_SEC",
    "LLM_TIMEOUT_PLANNER_PARAMETER_RESOLUTION_SEC",
    "LLM_TIMEOUT_PLANNER_TOOL_SELECTION_SEC",
    "LLM_TIMEOUT_POST_TOOL_ARTICULATOR_SEC",
    "LLM_TIMEOUT_POST_TOOL_OBSERVATION_SEC",
    "LLM_TIMEOUT_REFLECT_SEC",
    "LLM_TIMEOUT_REASONING_MAIN_SEC",
    "LLM_TIMEOUT_TOOL_CATEGORY_SELECTOR_SEC",
    "LLM_TIMEOUT_TOOL_OUTPUT_COMPRESSOR_SEC",
    "deployment_runtime_selection_identity",
    "has_versioned_runtime_selection_marker",
    "project_checkpoint_runtime_selection",
    "read_llm_timeout_planner_parameter_resolution_sec",
    "read_llm_timeout_planner_tool_selection_sec",
    "validate_reasoning_effort_for_model",
    "wait_for_with_timeout",
]
