"""Interactive TOML writer for one-shot managed-runner configuration."""

from __future__ import annotations

import getpass
import os
from pathlib import Path
from typing import Sequence

from drowai_runner.config import RunnerConfig

_DEFAULT_CAPABILITIES = (
    "docker",
    "file_comm",
    "pty",
    "terminal_stream_v1",
    "tool_command.v1",
    "tooling_plane.commands.v1",
)


def configure_runner_toml(
    *,
    config_path: Path,
    control_plane_url: str | None = None,
    install_token: str | None = None,
    tenant_id: int | None = None,
    tls_verify: bool | None = None,
    allow_insecure_cloud_endpoint: bool | None = None,
    interactive: bool = True,
) -> Path:
    """Write runner TOML from flags or prompts and validate the result."""
    normalized_url = _value_or_prompt(
        "Control-plane URL",
        control_plane_url,
        interactive=interactive,
    )
    normalized_token = _secret_or_prompt(
        "Install token",
        install_token,
        interactive=interactive,
    )
    normalized_tenant = tenant_id
    normalized_tls_verify = tls_verify
    if normalized_tls_verify is None:
        normalized_tls_verify = _bool_or_prompt(
            "Verify TLS certificates",
            default=True,
            interactive=interactive,
        )
    normalized_allow_insecure = allow_insecure_cloud_endpoint
    if normalized_allow_insecure is None:
        normalized_allow_insecure = not normalized_tls_verify or normalized_url.startswith("http://")

    config_path.parent.mkdir(parents=True, exist_ok=True)
    content = _build_toml(
        control_plane_url=normalized_url,
        install_token=normalized_token,
        tenant_id=normalized_tenant,
        tls_verify=normalized_tls_verify,
        allow_insecure_cloud_endpoint=normalized_allow_insecure,
        capabilities=_DEFAULT_CAPABILITIES,
    )
    config_path.write_text(content, encoding="utf-8")
    try:
        os.chmod(config_path, 0o600)
    except OSError:
        pass
    RunnerConfig.from_toml(config_path)
    return config_path


def _value_or_prompt(label: str, value: str | None, *, interactive: bool) -> str:
    cleaned = str(value or "").strip()
    if cleaned:
        return cleaned
    if not interactive:
        raise ValueError(f"{label} is required.")
    while True:
        cleaned = input(f"{label}: ").strip()
        if cleaned:
            return cleaned


def _secret_or_prompt(label: str, value: str | None, *, interactive: bool) -> str:
    cleaned = str(value or "").strip()
    if cleaned:
        return cleaned
    if not interactive:
        raise ValueError(f"{label} is required.")
    while True:
        cleaned = getpass.getpass(f"{label}: ").strip()
        if cleaned:
            return cleaned


def _bool_or_prompt(label: str, *, default: bool, interactive: bool) -> bool:
    if not interactive:
        return default
    suffix = "Y/n" if default else "y/N"
    raw = input(f"{label} [{suffix}]: ").strip().lower()
    if not raw:
        return default
    return raw in {"1", "true", "yes", "y", "on"}


def _build_toml(
    *,
    control_plane_url: str,
    install_token: str,
    tenant_id: int | None,
    tls_verify: bool,
    allow_insecure_cloud_endpoint: bool,
    capabilities: Sequence[str],
) -> str:
    capability_lines = ", ".join(f'"{item}"' for item in capabilities)
    return "\n".join(
        [
            "# Generated by drowai_runner configure.",
            "[runner]",
            'runner_root = "/var/lib/drowai"',
            'host_bind_root = "/var/lib/drowai"',
            f'control_plane_url = "{_escape_toml(control_plane_url)}"',
            f'registration_token = "{_escape_toml(install_token)}"',
            *([f"tenant_id = {int(tenant_id)}"] if tenant_id is not None else []),
            f"tls_verify = {str(bool(tls_verify)).lower()}",
            f"allow_insecure_cloud_endpoint = {str(bool(allow_insecure_cloud_endpoint)).lower()}",
            f"capabilities = [{capability_lines}]",
            "[runner.labels]",
            'deployment = "remote-runner-site"',
            "",
        ]
    )


def _escape_toml(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
