"""Task-admission reason-code contracts shared by admission and assignment.

Responsibilities:
- Provide one canonical source for API-facing admission rejection codes.
- Keep reason-code ownership centralized for quota and runner-capacity gates.
"""

USER_QUOTA_EXCEEDED = "USER_QUOTA_EXCEEDED"
TENANT_QUOTA_EXCEEDED = "TENANT_QUOTA_EXCEEDED"
RUNNER_CAPACITY_EXHAUSTED = "RUNNER_CAPACITY_EXHAUSTED"
GLOBAL_CAPACITY_EXHAUSTED = "GLOBAL_CAPACITY_EXHAUSTED"
NO_RUNNERS_REGISTERED = "NO_RUNNERS_REGISTERED"
RUNNER_NOT_ONLINE = "RUNNER_NOT_ONLINE"
RUNNER_STALE_OR_OFFLINE = "RUNNER_STALE_OR_OFFLINE"
RUNNER_EXECUTION_SITE_MISMATCH = "RUNNER_EXECUTION_SITE_MISMATCH"
RUNNER_CREDENTIAL_NOT_ACTIVE = "RUNNER_CREDENTIAL_NOT_ACTIVE"
RUNNER_PROTOCOL_INCOMPATIBLE = "RUNNER_PROTOCOL_INCOMPATIBLE"
RUNNER_RUNTIME_VERSION_INCOMPATIBLE = "RUNNER_RUNTIME_VERSION_INCOMPATIBLE"
RUNNER_CAPABILITY_MISMATCH = "RUNNER_CAPABILITY_MISMATCH"
RUNNER_LABEL_MISMATCH = "RUNNER_LABEL_MISMATCH"
RUNNER_MAINTENANCE_MODE = "RUNNER_MAINTENANCE_MODE"
RUNNER_REVOKED = "RUNNER_REVOKED"
RUNNER_HEARTBEAT_STALE = "RUNNER_HEARTBEAT_STALE"
