"""Generated setup artifact publication for deployment-specific runtimes.

This module keeps setup orchestration independent from Docker or local launcher
paths. It publishes generated files only after database provisioning has been
committed and uses atomic replacement so file existence is a reliable signal.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Protocol

from backend.config.generated_config import GeneratedConfigPaths, default_generated_paths


@dataclass(frozen=True, slots=True)
class RunnerConfigArtifact:
    """Material needed to publish runner enrollment for local runners."""

    install_token: str
    network: Mapping[str, object]
    management_url: str = "http://backend:8000"
    tls_verify: bool = False
    allow_insecure_management_url: bool = True


class GeneratedArtifactPublisher(Protocol):
    """Publishes generated setup artifacts after DB provisioning is durable."""

    def publish_runner_config(self, artifact: RunnerConfigArtifact) -> Path | None:
        """Publish runner enrollment when this deployment owns a local runner."""


class NoopGeneratedArtifactPublisher:
    """Publisher for Management profiles that do not own a local runner."""

    def publish_runner_config(self, artifact: RunnerConfigArtifact) -> Path | None:
        del artifact
        return None


class FilesystemGeneratedArtifactPublisher:
    """Publish generated artifacts under configured config/secrets roots."""

    def __init__(self, *, paths: GeneratedConfigPaths | None = None) -> None:
        self._paths = paths or default_generated_paths()

    def publish_runner_config(self, artifact: RunnerConfigArtifact) -> Path:
        """Atomically publish the local runner enrollment consumed by waiting runners."""
        config_path = self._paths.config_dir / "enrollment.toml"
        self._paths.config_dir.mkdir(parents=True, exist_ok=True)
        runner_root = str(os.getenv("DROWAI_RUNNER_ROOT") or "").strip() or "/var/lib/drowai"
        host_bind_root = str(os.getenv("DROWAI_RUNNER_HOST_BIND_ROOT") or "").strip() or runner_root
        network_label = str(artifact.network.get("kali_docker_network") or "drowai-platform").strip()
        control_plane_url = str(
            os.getenv("DROWAI_STANDALONE_RUNNER_CONTROL_PLANE_URL")
            or os.getenv("DROWAI_RUNNER_CONTROL_PLANE_URL")
            or artifact.management_url
        ).strip()
        content = build_runner_enrollment_toml(
            management_url=control_plane_url,
            enrollment_token=artifact.install_token,
            runner_root=runner_root,
            host_bind_root=host_bind_root,
            tls_verify=artifact.tls_verify,
            allow_insecure_management_url=artifact.allow_insecure_management_url,
            labels={
                "deployment": "standalone-management",
                "site": "local",
                "network": network_label,
            },
        )
        _atomic_write_text(config_path, content)
        return config_path


def build_runner_enrollment_toml(
    *,
    management_url: str,
    enrollment_token: str,
    runner_root: str = "/var/lib/drowai",
    host_bind_root: str = "/var/lib/drowai",
    tls_verify: bool = True,
    allow_insecure_management_url: bool | None = None,
    labels: Mapping[str, object] | None = None,
) -> str:
    """Build the pre-registration runner enrollment TOML."""
    allow_insecure = (
        bool(allow_insecure_management_url)
        if allow_insecure_management_url is not None
        else str(management_url).strip().startswith("http://")
    )
    lines = [
        "# Generated by DrowAI Management; do not edit for product deployment.",
        "[runner]",
        f"runner_root = {_toml_string(runner_root)}",
        f"host_bind_root = {_toml_string(host_bind_root)}",
        f"control_plane_url = {_toml_string(management_url)}",
        f"registration_token = {_toml_string(enrollment_token)}",
        f"tls_verify = {str(bool(tls_verify)).lower()}",
        f"allow_insecure_cloud_endpoint = {str(allow_insecure).lower()}",
        'capabilities = ["docker", "file_comm", "pty", "terminal_stream_v1", "tool_command.v1", "tooling_plane.commands.v1"]',
        "[runner.labels]",
    ]
    for key, value in sorted(dict(labels or {}).items()):
        normalized_key = str(key).strip()
        if normalized_key:
            lines.append(f"{normalized_key} = {_toml_string(str(value))}")
    lines.append("")
    return "\n".join(lines)


def default_generated_artifact_publisher(*, deployment_profile: str | None = None) -> GeneratedArtifactPublisher:
    """Return the publisher appropriate for the active deployment profile."""
    profile = str(deployment_profile or os.getenv("DROWAI_DEPLOYMENT_PROFILE") or "").strip().lower()
    if profile == "distributed":
        return NoopGeneratedArtifactPublisher()
    return FilesystemGeneratedArtifactPublisher()


def _atomic_write_text(target: Path, content: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    temp_path = target.with_name(f".{target.name}.tmp-{os.getpid()}")
    file_descriptor = os.open(str(temp_path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8", closefd=False) as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
    finally:
        os.close(file_descriptor)
    try:
        os.chmod(temp_path, 0o600)
    except OSError:
        pass
    os.replace(temp_path, target)
    try:
        os.chmod(target, 0o600)
    except OSError:
        pass


def _toml_string(value: str) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
